language: c

sudo: required

dist: xenial

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false

before_install:
  - curl -OLs https://raw.githubusercontent.com/isomorphisms/r-travis/xenial/scripts/travis-tool.sh && chmod 0755 travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_aptget r-cran-zoo r-cran-xts r-cran-ttr r-cran-curl

script:
  - ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: win@isomorphism.es   #change
    on_failure: lose@isomorphism.es  #change

